// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

#include <OB/CORBAClient.h>
#include <upTime.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030200L)
#       error ORBacus version mismatch!
#   endif
#endif

::OB::TypeCodeConst _tc_upTime(
"010000000e00000023000000010000000f00000049444c3a757054696d653a312e30000007000"
"000757054696d6500"
);

//
// IDL:upTime:1.0
//
const char* upTime::ids_[] =
{
    "IDL:upTime:1.0",
    0
};

void
OBDuplicate(upTime_ptr p)
{
    if(p)
        p -> _add_ref();
}

void
OBRelease(upTime_ptr p)
{
    if(p)
        p -> _remove_ref();
}

upTime_ptr
upTime::_narrow(::CORBA::Object_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        upTime_ptr v = 
            dynamic_cast< upTime_ptr >(p);
        if(v)
            return _duplicate(v);

        if(p -> _is_a(ids_[0]))
        {
            OBProxy_upTime* val = new OBProxy_upTime;
            val -> _OB_copyFrom(p);
            return val;
        }
    }

    return _nil();
}

upTime_ptr
upTime::_narrow(::CORBA::AbstractBase_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        upTime_ptr v =
            dynamic_cast< upTime_ptr >(p);
        if(v)
            return _duplicate(v);

        ::CORBA::Object_var obj = p -> _to_object();
        return _narrow(obj);
    }
    return _nil();
}

upTime_ptr
upTime::_unchecked_narrow(::CORBA::Object_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        upTime_ptr v =
            dynamic_cast< upTime_ptr >(p);
        if(v)
            return _duplicate(v);

        OBProxy_upTime* val = new OBProxy_upTime;
        val -> _OB_copyFrom(p);
        return val;
    }

    return _nil();
}

upTime_ptr
upTime::_unchecked_narrow(::CORBA::AbstractBase_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        ::CORBA::Object_var obj = p -> _to_object();
        return _unchecked_narrow(obj);
    }
    return _nil();
}

const char**
upTime::_OB_staticIds()
{
    return ids_;
}

void
OBMarshal(upTime_ptr _ob_v, OB::OutputStreamImpl* _ob_out)
{
    _ob_out -> write_Object(_ob_v);
}

void
OBUnmarshal(upTime_ptr& _ob_v, OB::InputStreamImpl* _ob_in)
{
    upTime_var old = _ob_v;
    ::CORBA::Object_var p = _ob_in -> read_Object();

    if(!::CORBA::is_nil(p))
    {
        OBProxy_upTime* _ob_obj = new OBProxy_upTime;
        _ob_obj -> _OB_copyFrom(p);
        _ob_v = _ob_obj;
    }
    else
        _ob_v = upTime::_nil();
}

void
operator<<=(::CORBA::Any& any, upTime_ptr* v)
{
    any.replace(_tc_upTime, (::CORBA::Object_ptr)*v, true);
}

void
operator<<=(::CORBA::Any& any, upTime_ptr v)
{
    upTime_ptr val = upTime::_duplicate(v);
    any <<= &val;
}

::CORBA::Boolean
operator>>=(const ::CORBA::Any& any, upTime_ptr& v)
{
    if(any.check_type(_tc_upTime))
    {
        ::CORBA::Object_ptr val = (::CORBA::Object_ptr)any.value();

        if(!::CORBA::is_nil(val))
        {
            if(!(v = dynamic_cast< upTime_ptr >(val)))
            {
                OBProxy_upTime* obj = new OBProxy_upTime;
                obj -> _OB_copyFrom(val);
                v = obj;
                (::CORBA::Any&)any <<= &v;
            }
        }
        else
            v = upTime::_nil();

        return true;
    }
    else
        return false;
}

//
// IDL:upTime:1.0
//
OB::MarshalStubImpl_ptr
OBProxy_upTime::_OB_createMarshalStubImpl()
{
    return new OBMarshalStubImpl_upTime;
}

const char**
OBProxy_upTime::_OB_ids() const
{
    return ::upTime::ids_;
}

//
// IDL:upTime/getUpTime:1.0
//
void
OBProxy_upTime::getUpTime(::CORBA::Float_out _ob_a0,
                          ::CORBA::Float_out _ob_a1)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_upTime_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_upTime_ptr>(_ob_stubImplBase.in());
            _ob_stubImpl -> getUpTime(_ob_a0, _ob_a1);
            return;
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:upTime:1.0
//
void
OBDuplicate(OBStubImpl_upTime_ptr p)
{
    if(p)
        p -> _OB_incRef();
}

void
OBRelease(OBStubImpl_upTime_ptr p)
{
    if(p)
        p -> _OB_decRef();
}

//
// IDL:upTime/getUpTime:1.0
//
void
OBMarshalStubImpl_upTime::getUpTime(::CORBA::Float_out _ob_a0,
                                    ::CORBA::Float_out _ob_a1)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("getUpTime", true);
        try
        {
            _OB_preMarshal(_ob_down);
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            bool _ob_uex;
            OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_down, _ob_uex);
            if(_ob_uex)
            {
                _OB_postUnmarshal(_ob_down);
            }
            else
            {
                try
                {
                    _ob_a0 = _ob_in -> read_float();
                    _ob_a1 = _ob_in -> read_float();
                }
                catch(const ::CORBA::SystemException& _ob_ex)
                {
                    _OB_unmarshalEx(_ob_down, _ob_ex);
                }
                _OB_postUnmarshal(_ob_down);
                return;
            }
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}
