// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//export OMNIORB_CONFIG=/etc/omniORB.cfg
// **********************************************************************

// Version: 4.3.2

#include <OB/CORBAServer.h>
#include <upTime_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030200L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:upTime/getUpTime:1.0
//
void
POA_upTime::_OB_op_getUpTime(OB::Upcall_ptr _ob_up)
{
    ::CORBA::Float _ob_a0;
    ::CORBA::Float _ob_a1;
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    getUpTime(_ob_a0, _ob_a1);
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_out -> write_float(_ob_a0);
    _ob_out -> write_float(_ob_a1);
    _OB_postMarshal(_ob_up);
}

//
// IDL:upTime:1.0
//
::CORBA::Boolean
POA_upTime::_is_a(const char* type)
    throw(::CORBA::SystemException)
{
    const char** _ob_ids = upTime::_OB_staticIds();
    for(::CORBA::ULong _ob_i = 0; _ob_ids[_ob_i] != 0; ++_ob_i)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

::CORBA::RepositoryId
POA_upTime::_primary_interface(const PortableServer::ObjectId&,
                               PortableServer::POA_ptr)
{
    return ::CORBA::string_dup(upTime::_OB_staticIds()[0]);
}

upTime_ptr
POA_upTime::_this()
{
    ::CORBA::Object_var obj = _OB_createReference();
    upTime_var result = upTime::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_upTime::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                     const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_upTime(poa, oid, this);
}

void
POA_upTime::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "getUpTime"
    };
    static const ::CORBA::ULong _ob_numNames = 1;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // getUpTime
        _OB_op_getUpTime(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:upTime:1.0
//
OBDirectStubImpl_upTime::OBDirectStubImpl_upTime(
    PortableServer::POA_ptr poa,
    const PortableServer::ObjectId& oid,
    PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    _ob_initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:upTime/getUpTime:1.0
//
void
OBDirectStubImpl_upTime::getUpTime(::CORBA::Float_out _ob_a0,
                                   ::CORBA::Float_out _ob_a1)
{
    OB::InvocationHandler _ob_handler(this, "getUpTime");
    dynamic_cast<POA_upTime*>(_ob_servant_) -> getUpTime(_ob_a0, _ob_a1);
}
